options:
  plugins:
    type: string
    default: 'default'
    description: >
      Comma separated list of plugins to enable. If set to "default"
      list of plugins will match defaults shipped with Ubuntu package
  graphite_host:
    type: string
    description: Graphite hostname or IP address
  graphite_port:
    type: int
    default: 2003
    description: Graphite port number
  graphite_protocol:
    type: string
    default: 'TCP'
    description: TCP or UDP
  prefix:
    type: string
    default: 'collectd.'
    description: Prepended to unit hostname
  interval:
    type: int
    default: 10
    description: Interval at which to query values
  nagios_context:
    default: "juju"
    type: string
    description: |
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like:
          juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  nagios_servicegroups:
    default: "juju"
    type: string
    description: |
      Comma separated list of nagios servicegroups for the graphite check
