options:
  plugins:
    type: string
    default: 'default'
    description: >
      Comma separated list of plugins to enable. If set to "default"
      list of plugins will match defaults shipped with Ubuntu package
  interval:
    type: int
    default: 10
    description: Interval at which to query values by default
  graphite_endpoint:
    type: string
    description: >
      Optional graphite hostname(or IP) and port. For example:
          graphite.example.com:2003
      If set write_graphite will be enabled and configured
  graphite_protocol:
    type: string
    default: 'TCP'
    description: TCP or UDP. Only used if graphite_endpoint is set
  graphite_prefix:
    type: string
    default: 'collectd.'
    description: Prepended to unit hostname in graphite. Only used in graphite_endpoint is set
  nagios_context:
    default: "juju"
    type: string
    description: |
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like:
          juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  nagios_servicegroups:
    default: "juju"
    type: string
    description: |
      Comma separated list of nagios servicegroups for the graphite check
